name: CI

on:
  workflow_dispatch

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "flyway"
          ext: ".sql"
  Test:
    runs-on: ubuntu-latest
    needs: list-files
    steps:
      - name: Output results
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          data: '${{ needs.list-files.outputs.paths }}'
      

