name: CI

on:
  push:
    paths:
      - flyway/**

jobs:
  # -------------------------------------------------------------
  # Using GitHub's API is not supported for push events
  # -------------------------------------------------------------
  # 
  # ----------------------------------------------------------------------------------------------
  # Using local .git history
  # ----------------------------------------------------------------------------------------------
  # Event `push`: Compare the preceding remote commit -> to the current commit of the main branch 
  # ----------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: List SQL files in Flyway folder
        run: |
          find flyway -type f -name "*.sql" | xargs -n 1 basename > file_list.txt

      - name: Create array of file names
        id: create-array
        run: |
          echo "::set-output name=file_names::$(cat file_list.txt)"
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          data: "$(cat file_names.json)"
      

