name: Flyway Changed
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
jobs:
  send-summary:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
    - uses: johannes-huther/webhook.sh@v1
      env:
        webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
