name: Check for New Files

on:
  push:
    branches: [ main ]  # Replace with your desired branch

jobs:
  check_new_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Determine new files
        run: |
          # Replace 'your_folder' with the actual folder path
          new_files=$(git diff --name-only HEAD^ HEAD 'flyway/sql' | grep '^A ')
          if [ -n "$new_files" ]; then
            echo "New files detected:"
            echo "$new_files"
            # Replace with your webhook URL and desired payload format
            curl -X POST 	https://webhook.site/a48123de-0687-45dd-8d3f-8401497d13f9 -H "Content-Type: application/json" -d "{\"files\":[$new_files]}"
          fi
