name: DevAutomation

on:
  workflow_dispatch

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "flyway"
          ext: ".sql"
  Test:
    runs-on: ubuntu-latest
    needs: list-files
    steps:
      - name: Output results
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: 'https://hook.eu2.make.com/1plfm86487lbxrvq8siu1lhh8pqxbcp9'
          event_name: ${{ github.actor }}
          data: '${{ needs.list-files.outputs.paths }}'
      

