name: Post to Webhook

on:
  workflow_dispatch:

jobs:
  post_to_webhook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # this is the new step
    - uses: dchourasia/ms-teams-notification@1.0 #  or "./" if in a local set-up
      if: always()
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
